default:
    image: python:3.9
    before_script:
       - apt-get update
       - apt-get install -y python3-pip netcdf-bin
       - pip install -r requirements.txt
stages:
    - test
    - linting
test:
  script:
    - pytest
    - ls -lh sample_data/*.nc
    - find -name "*.nc"

pylint:
  stage: linting
  image: registry.gitlab.com/pipeline-components/pylint:latest
  script:
    - pylint --exit-zero --load-plugins=pylint_gitlab --output-format=gitlab-codeclimate:codeclimate.json **/*.py
  artifacts:
    reports:
      codequality: codeclimate.json
    when: always