default:
    image: python:3.9
    before_script:
       - apt-get update
       - apt-get install -y python3-pip netcdf-bin
       - pip install -r requirements.txt
       - pip install pylint
stages:
    - test
    - static analysis
test:
  script:
    - pytest
    - ls -lh sample_data/*.nc
    - find -name "*.nc"


pylint:
  stage: static analysis
  allow_failure: true
  script:
    - pylint --fail-under=8 pylint **/*.py *.py
  artifacts:
    when: always
    reports:
      codequality: codeclimate.json

