default:
    image: python:3.9
    before_script:
       - apt-get update
       - apt-get install -y python3-pip netcdf-bin
       - pip install -r requirements.txt
stages:
    - test
test:
  script:
    - pytest
    - ls -lh sample_data/*.nc
    - find -name "*.nc"