port: '/dev/ttyUSB0'
baud: 19200
Parsivel_name: PAR008
Parsivel_ID: 008
station_site: 'Delft'  # add prefix Camp for a campaign ie CampRotterdam
station_name: 'GV' # keep under 10 characters, max accepted by Parsivel
script_name: 'capture_disdro_data.py'
data_dir: '/data/disdroDL/'
log_dir: '/var/log/disdroDL/'

telegram_fields:
  '01':
      name: Rain intensity
      unit: "mm/h"
  '02':
      name: Rain amount accumulated 
      unit: "mm"
  '03':
      name: Weather code to SYNOP waw
  '04':
      name: Weather code to SYNOP ww
  '05':
      name: Weather code METAR/SPECI
  '06':
      name: Weather code according to NWS 
  '07':
      name: Radar reflectivity 
      unit: "dBz"
  '08':
      name: MOR visibility in precipitation 
      unit: "m"
  '09':
      name: Sample interval 
      unit: "s"
  '10':
      name: Signal amplitude of the laser strip
  '11':
      name: Number of particles detected and validated
  '12':
      name: Temperature in the sensor housing 
      unit: "°C"
  '13':
      name: Sensor serial number
  '14':
      name: Firmware IOP version number
  '15':
      name: Firmware DSP version number
  '16':
      name: Sensor head heating current 
      unit: "A"
  '17':
      name: Power supply voltage 
      unit: "V"
  '18':
      name: Sensor status
  '19':
      name: Date/time measuring start
  '20':
      name: Sensor time
  '21':
      name: Sensor date
  '22':
      name: Station name
  '23':
      name: Station number
  '24':
      name: Rain amount absolute 
      unit: "mm"
  '25':
      name: Error code
  '26':
      name: Temperature PCB 
      unit: "°C"
  '27':
      name: Temperature right sensor head 
      unit: "°C"
  '28':
      name: Temperature left sensor head 
      unit: "°C"
  '30':
      name: Rain intensity max. 30.000 mm/h
      unit: "mm/h"
  '31':
      name: Rain intensity max. 1200.0 mm/h
      unit: "mm/h"
  '32':
      name: Rain amount accumulate 
      unit: "mm"
  '33':
      name: Radar reflectivity
      unit: "dBz"
  '34':
      name: Kinetic energy 
      unit: "J/(m^2h)"
  '35':
      name: Snow depth intensity
      unit: "mm/h"
  '60':
      name: Number of all particles detected
  '61':
      name: List of all particles detected (particle-size speed)
      unit: "mm, mm/h"
  '90':
      name: Field N
      unit: "log10 (1/m^3 mm)"
  '91':
      name: Field v
      unit: "m/s"
  '93':
      name: Raw data