# sensor and script settings
station_code: 'SLUFTER' # keep under 10 characters, max accepted by Parsivel
port: '/dev/ttyUSB0'
baud: 19200
script_name: 'main.py'
data_dir: '/data/disdroDL/'
db_filename: 'disdrodl.db'
log_dir: '/var/log/disdroDL/'

######### NETCDF ###########
# global attributes (all will be written to netCDF as global attributes)
global_attrs:
    title: 'OTT Parsivel2 disdrometer data'
    institution: 'Delft University of Technology'
    source: 'surface observation'
    history: '-'
    netcdf_version: '0.1.0'
    Conventions: 'CF-1.7'
    site_name: 'TNO_Slufter'
    sensor_name: PAR006
    project_name: 'https://ruisdael-observatory.nl/'
    contributors: 'Marc Schleiss, Andre Castro, Rob Mackenzie, Mahaut Sourzac, Saverio Guzzo, Vasil Chirov, Mels Lutgerink, Ella Milinovic, Noky Soekarman, Jesse Vleeschdraager'
    sensor_type: 'OTT Hydromet Parsivel2'
    sensor_serial_number: '450906'

variables:
    latitude:
        dimensions: # empty for scalar variables
        dtype: 'f4'  # 32bit floating point
        value: 
            - 51.933496
        include_in_nc: 'always'                    
        var_attrs: 
            units: 'degree_north'
            long_name: 'Latitude of site'
            standard_name: 'latitude'
    longitude:
        dimensions:  # empty for scalar variables
        dtype: 'f4'  # 32bit floating point
        value: 
            - 3.999849
        include_in_nc: 'always'                    
        var_attrs: 
            units: 'degree_east'
            long_name: 'Longitude of site'
            standard_name: 'longitude'
    altitude:
        dimensions:  # empty for scalar variables
        dtype: 'f4'  # 32bit floating point
        value: 
            - 3
        include_in_nc: 'always'                    
        var_attrs: 
            units: 'm'
            long_name: 'Altitude of site'
            standard_name: 'altitude'
